### ISSUE TITLE
Создать модель по определению объекта в кадре

### ISSUE THREAD

**Issue by compfee** [compfee/RoboticArm#1]
CNN модель

**Comment by Ane1y** [comment]
Implementation was added in 1c44a8804caf7e75b5d6998907da61541a1a1377

**Comment by compfee** [comment]
Проверено
Все работает!!
Спасибо, коллега, за оперативную работу!!

**Comment by Ane1y** [comment]
> Проверено Все работает!! Спасибо, коллега, за оперативную работу!!

Отлично, коллега!

**Comment by compfee** [comment]
> > Проверено Все работает!! Спасибо, коллега, за оперативную работу!!
> 
> Отлично, коллега!

Продолжаем работу в том же духе!
