### ISSUE TITLE
Исследовать вопрос передачи сообщений между Raspberry Pi и Arduino Uno

### ISSUE THREAD

**Issue by compfee** [compfee/RoboticArm#10]

**Comment by Ane1y** [comment]
Можно осуществить передачу информации несколькими способами. Например, по USB или через RX/TX. Неплохая статья: https://www.aranacorp.com/en/serial-communication-between-raspberry-pi-and-arduino/. Тут обращаются к ACM "/dev/ttyACM0" со скоростью 9600. Можно также реализовать подключение к "/dev/ttyACM1" через блок try/catch. 

Тут: https://www.digikey.com/en/maker/blogs/2020/how-to-communicate-between-arduino-boards-and-raspberry-pi-sbcs рассматривается подсоединение через RX/TX, но нужно учесть, что напрямую подключать наверное не стоит, так как на пинах разное напряжение

**Comment by compfee** [comment]
Благодарю, коллега!!
Хороший отчет!!
