### ISSUE TITLE
Загрузить актуальную модель нейронной сети

### ISSUE THREAD

**Issue by compfee** [compfee/RoboticArm#13]
Необходимо по мере пополнения набора данных загружать актуальные модели нейронной сети с хорошими результатами выделения (>80%)

**Comment by compfee** [comment]
3950a735c199b454fa9de8c95c04b1a26c4058a6

**Comment by compfee** [comment]
a7b1aa83ad9476ba07d8db585a5b366bb864a5ed

**Comment by compfee** [comment]
0e2153bed2b83d80a3a3b986aae39a476b33e162

**Comment by Ane1y** [comment]
3c35ee3f1084f2a604f179e2e7ae168bcef6d888

**Comment by Ane1y** [comment]
129af70a8182e18ef41480356f3bb3128d10eb73
